# Generated by Django 2.2.24 on 2021-07-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cls', models.CharField(max_length=50)),
                ('sub', models.CharField(max_length=50)),
                ('marks', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
